name: Auto Version & Tag

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: ["iOS Build"]
    types:
      - completed

jobs:
  auto-version:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Generate version
      id: version
      run: |
        # Get current date for version
        DATE=$(date +'%Y.%m.%d')
        
        # Get commit count for today
        COMMIT_COUNT=$(git log --oneline --since="$(date +'%Y-%m-%d')" | wc -l)
        
        # Generate version: YYYY.MM.DD.COMMIT_COUNT
        VERSION="${DATE}.${COMMIT_COUNT}"
        
        echo "Generated version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Create and push tag
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        
        # Create tag
        git tag "v$VERSION"
        
        # Push tag
        git push origin "v$VERSION"
        
        echo "Created and pushed tag: v$VERSION"
        
    - name: Update version in app.json
      working-directory: ./react-native
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        
        # Update version in app.json
        node -e "
          const fs = require('fs');
          const appJson = JSON.parse(fs.readFileSync('app.json', 'utf8'));
          appJson.version = '$VERSION';
          fs.writeFileSync('app.json', JSON.stringify(appJson, null, 2));
        "
        
    - name: Commit version update
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add react-native/app.json
        git commit -m "Bump version to ${{ steps.version.outputs.version }}" || echo "No changes to commit"
        git push origin master
        
    - name: Output version info
      run: |
        echo "✅ Version ${{ steps.version.outputs.version }} created and tagged"
        echo "📦 Ready for deployment" 