name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      auto_approve:
        description: 'Auto approve changes (use with caution)'
        required: false
        default: false
        type: boolean

env:
  TF_VERSION: "1.5.0"
  AWS_REGION: "us-east-1"

jobs:
  validate:
    name: Validate Terraform Configuration
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Format Check
      run: |
        cd iac/terraform
        terraform fmt -check -recursive || true

    - name: Terraform Init
      run: |
        cd iac/terraform/environments/staging
        terraform init

    - name: Terraform Validate
      run: |
        cd iac/terraform/environments/staging
        terraform validate

  plan-staging:
    name: Plan Staging Changes
    runs-on: ubuntu-latest
    needs: validate
    if: github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply'
    environment: staging
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: |
        cd iac/terraform/environments/staging
        terraform init

    - name: Terraform Plan
      id: plan
      run: |
        cd iac/terraform/environments/staging
        terraform plan -out=tfplan
        terraform show -no-color tfplan > plan.txt
      continue-on-error: true

    - name: Comment Plan
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      env:
        PLAN: "${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Plan 📋
          \`\`\`\n
          ${process.env.PLAN || 'No changes. Infrastructure is up-to-date.'}
          \`\`\`
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event.inputs.action }}\`, Environment: \`staging\`*`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v4
      with:
        name: staging-plan
        path: iac/terraform/environments/staging/plan.txt

  apply-staging:
    name: Apply Staging Changes
    runs-on: ubuntu-latest
    needs: plan-staging
    if: github.event.inputs.action == 'apply' && github.event.inputs.environment == 'staging'
    environment: staging
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: |
        cd iac/terraform/environments/staging
        terraform init

    - name: Terraform Apply
      run: |
        cd iac/terraform/environments/staging
        terraform apply -auto-approve

    - name: Get Staging Outputs
      id: staging-outputs
      run: |
        cd iac/terraform/environments/staging
        echo "alb_dns_name=$(terraform output -raw alb_dns_name)" >> $GITHUB_OUTPUT
        echo "ecr_repository_url=$(terraform output -raw ecr_repository_url)" >> $GITHUB_OUTPUT

    - name: Comment Apply Results
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Apply ✅ Staging
          **Status:** Successfully applied to staging environment
          
          **Outputs:**
          - ALB DNS: \`${{ steps.staging-outputs.outputs.alb_dns_name }}\`
          - ECR Repository: \`${{ steps.staging-outputs.outputs.ecr_repository_url }}\`
          
          *Pusher: @${{ github.actor }}, Environment: \`staging\`*`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

  plan-production:
    name: Plan Production Changes
    runs-on: ubuntu-latest
    needs: [validate, apply-staging]
    if: github.event.inputs.action == 'apply' && github.event.inputs.environment == 'production'
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: |
        cd iac/terraform/environments/production
        terraform init

    - name: Terraform Plan
      id: plan
      run: |
        cd iac/terraform/environments/production
        terraform plan -out=tfplan
        terraform show -no-color tfplan > plan.txt
      continue-on-error: true

    - name: Comment Plan
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      env:
        PLAN: "${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Plan 📋 Production
          \`\`\`\n
          ${process.env.PLAN || 'No changes. Infrastructure is up-to-date.'}
          \`\`\`
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event.inputs.action }}\`, Environment: \`production\`*`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v4
      with:
        name: production-plan
        path: iac/terraform/environments/production/plan.txt

  apply-production:
    name: Apply Production Changes
    runs-on: ubuntu-latest
    needs: plan-production
    if: github.event.inputs.action == 'apply' && github.event.inputs.environment == 'production'
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: |
        cd iac/terraform/environments/production
        terraform init

    - name: Terraform Apply
      run: |
        cd iac/terraform/environments/production
        terraform apply -auto-approve

    - name: Get Production Outputs
      id: production-outputs
      run: |
        cd iac/terraform/environments/production
        echo "alb_dns_name=$(terraform output -raw alb_dns_name)" >> $GITHUB_OUTPUT
        echo "ecr_repository_url=$(terraform output -raw ecr_repository_url)" >> $GITHUB_OUTPUT

    - name: Comment Apply Results
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Apply ✅ Production
          **Status:** Successfully applied to production environment
          
          **Outputs:**
          - ALB DNS: \`${{ steps.production-outputs.outputs.alb_dns_name }}\`
          - ECR Repository: \`${{ steps.production-outputs.outputs.ecr_repository_url }}\`
          
          *Pusher: @${{ github.actor }}, Environment: \`production\`*`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          }) 